### ISSUE TITLE
Update documentation with changes up to 1.2.0

### ISSUE THREAD

**Issue by JonTheNiceGuy** [E-and-CS/fortigate_policy#10]
Includes:

* In rules, lists of one item can be stated as a string:
```
rulegroup10:
  rule01:
    sources: AddressObject
    destinations: AddressObject
    services: ServiceObject
```
(Instead of `sources:\r-` for single objects)
