### ISSUE TITLE
VIP groups are not created when clustering in groups

### ISSUE THREAD

**Issue by JonTheNiceGuy** [E-and-CS/fortigate_policy#11]
Example code:

```yaml
example_address_object:
  example_vip_1:
    real_ip: 192.0.2.1
    real_port: 80
    vip_ip: 198.51.100.1
  example_vip_2:
    real_ip: 192.0.2.2
    real_port: 80
    vip_ip: 198.51.100.2

example_address_group:
  example_vip:
  - example_vip_1
  - example_vip_2
```

Desired behaviour: Created VIP group with VIP items
Actual behaviour: Attempt to create Address Group with VIP items. Fail.

Initial troubleshooting: Requires FortiOS VIP Group module, detection of VIP group (versus Address group), and subsequent creation thereof.
